### ISSUE TITLE
ghc-parser-0.1.6.0 does not compile

### ISSUE THREAD

**Issue by peti** [gibiansky/IHaskell#494]
Citing from http://hydra.cryp.to/build/882729/nixlog/3/raw:

~~~~~~
Configuring ghc-parser-0.1.6.0...
Warning: 'hs-source-dirs: src-7.10' directory does not exist.
[...]
Building ghc-parser-0.1.6.0...
Preprocessing library ghc-parser-0.1.6.0...
Setup: can't find source for Language/Haskell/GHC/HappyParser in generic-src,
src-7.10, dist/build/autogen
~~~~~~

**Comment by gibiansky** [comment]
Fixed in `master`, I believe. Just uploaded new version `0.1.7` to Hackage, please re-open issue if it also has the same bug. (Also uploaded `ihaskell-0.6.3` which requires newest ghc-parser)

@sumitsahrawat Note that for Docker images you should now use `ihaskell-0.6.3` (it doesn't really matter, but since it exists I figured I'd ping you)

**Comment by pschmied** [comment]
Hi there,

I think this may still be an issue in 0.1.7 (I'm trying to build ihaskell, FYI). If it makes any difference, I'm on OpenBSD 5.8-Snapshot, using the packaged version of the haskell-platform and installing in a new sandbox:

    maui% mkdir ghc-parser
    maui% cd ghc-parser 
    maui% cabal sandbox init
    Writing a default package environment file to
    /home/peter/ghc-parser/cabal.sandbox.config
    Creating a new sandbox at /home/peter/ghc-parser/.cabal-sandbox
    maui% cabal update  
    Downloading the latest package list from hackage.haskell.org
    Note: there is a new version of cabal-install available.
    To upgrade, run: cabal install cabal-install
    maui% cabal install cabal-install
    Resolving dependencies...
    Notice: installing into a sandbox located at
    /home/peter/ghc-parser/.cabal-sandbox
    Configuring Cabal-1.22.4.0...
    Building Cabal-1.22.4.0...
    Installed Cabal-1.22.4.0
    Configuring cabal-install-1.22.6.0...
    Building cabal-install-1.22.6.0...
    Installed cabal-install-1.22.6.0
    maui% cabal install ghc-parser
    Resolving dependencies...
    Notice: installing into a sandbox located at
    /home/peter/ghc-parser/.cabal-sandbox
    Configuring ghc-parser-0.1.7.0...
    Failed to install ghc-parser-0.1.7.0
    Last 10 lines of the build log ( /home/peter/ghc-parser/.cabal-sandbox/logs/ghc-parser-0.1.7.0.log ):
    [1 of 1] Compiling Main             ( /tmp/ghc-parser-0.1.7.0-13346/ghc-parser-0.1.7.0/Setup.hs, /tmp/ghc-parser-0.1.7.0-13346/ghc-parser-0.1.7.0/dist/dist-sandbox-9e86e78a/setup/Main.o )
    Linking /tmp/ghc-parser-0.1.7.0-13346/ghc-parser-0.1.7.0/dist/dist-sandbox-9e86e78a/setup/setup ...
    /bin/sh: ./build-parser.sh: No such file or directory
    Configuring ghc-parser-0.1.7.0...
    Warning: 'hs-source-dirs: src-7.8.3' directory does not exist.
    setup: user error (The program cpphs is required but it could not be found.)
    cabal: user error (Error: some packages failed to install:
    ghc-parser-0.1.7.0 failed during the configure step. The exception was:
    ExitFailure 1
    )
    maui%

**Comment by pschmied** [comment]
Oops, my failure to read carefully. I see that I should be installing happy and cpphs first. There may be a build error, but I'm going to try again--this time with reading comprehension.

**Comment by pschmied** [comment]
Fairly certain now that I'm building things as per instructions, but am still encountering barfage when building ghc-parser.


    maui% mkdir ihaskell
    maui% cd ihaskell 
    maui% cabal sandbox init
    Writing a default package environment file to
    /home/peter/ihaskell/cabal.sandbox.config
    Creating a new sandbox at /home/peter/ihaskell/.cabal-sandbox
    maui% cabal update
    Downloading the latest package list from hackage.haskell.org
    Skipping download: Local and remote files match.
    Note: there is a new version of cabal-install available.
    To upgrade, run: cabal install cabal-install
    maui% cabal install cabal-install
    Resolving dependencies...
    Notice: installing into a sandbox located at
    /home/peter/ihaskell/.cabal-sandbox
    Configuring Cabal-1.22.4.0...
    Building Cabal-1.22.4.0...
    Installed Cabal-1.22.4.0
    Configuring cabal-install-1.22.6.0...
    Building cabal-install-1.22.6.0...
    Installed cabal-install-1.22.6.0
    maui% cabal install happy cpphs
    Resolving dependencies...
    Notice: installing into a sandbox located at
    /home/peter/ihaskell/.cabal-sandbox
    Configuring happy-1.19.5...
    Configuring polyparse-1.11...
    Building polyparse-1.11...
    Building happy-1.19.5...
    Installed polyparse-1.11
    Configuring cpphs-1.19.2...
    Building cpphs-1.19.2...
    Installed cpphs-1.19.2
    Installed happy-1.19.5
    maui% cabal install ihaskell --reorder-goals
    Resolving dependencies...
    Notice: installing into a sandbox located at
    /home/peter/ihaskell/.cabal-sandbox
    Configuring ansi-terminal-0.6.2.2...
    Configuring base64-bytestring-1.0.0.1...
    Configuring SHA-1.6.4.2...
    Configuring byteable-0.1.1...
    Downloading transformers-compat-0.4.0.4...
    Building ansi-terminal-0.6.2.2...
    Building base64-bytestring-1.0.0.1...
    Building SHA-1.6.4.2...
    Building byteable-0.1.1...
    Installed byteable-0.1.1
    Installed base64-bytestring-1.0.0.1
    Configuring blaze-builder-0.4.0.1...
    Configuring cereal-0.4.1.1...
    Configuring cmdargs-0.10.13...
    Installed ansi-terminal-0.6.2.2
    Building blaze-builder-0.4.0.1...
    Building cereal-0.4.1.1...
    Building cmdargs-0.10.13...
    Configuring data-default-class-0.0.1...
    Installed blaze-builder-0.4.0.1
    Building data-default-class-0.0.1...
    Configuring dlist-0.7.1.1...
    Installed data-default-class-0.0.1
    Building dlist-0.7.1.1...
    Configuring extra-1.4.1...
    Installed cereal-0.4.1.1
    Configuring ghc-parser-0.1.7.0...
    Installed dlist-0.7.1.1
    Building extra-1.4.1...
    Configuring haskell-src-exts-1.16.0.1...
    Installed cmdargs-0.10.13
    Building haskell-src-exts-1.16.0.1...
    Configuring hourglass-0.2.9...
    Installed extra-1.4.1
    Building hourglass-0.2.9...
    Building ghc-parser-0.1.7.0...
    Configuring hscolour-1.23...
    Failed to install ghc-parser-0.1.7.0
    Last 10 lines of the build log ( /home/peter/ihaskell/.cabal-sandbox/logs/ghc-parser-0.1.7.0.log ):
    Building ghc-parser-0.1.7.0...
    Preprocessing library ghc-parser-0.1.7.0...
    setup: user error (can't find source for Language/Haskell/GHC/HappyParser in
    generic-src, src-7.8.3, dist/dist-sandbox-2fb860e3/build/autogen)
    Building hscolour-1.23...
    Configuring mime-types-0.1.0.6...
    Installed hourglass-0.2.9
    Building mime-types-0.1.0.6...
    Configuring memory-0.8...
    Installed mime-types-0.1.0.6
    Building memory-0.8...
    Configuring nats-1...
    Installed hscolour-1.23
    Configuring network-info-0.2.0.7...
    Installed memory-0.8
    Building nats-1...
    Building network-info-0.2.0.7...
    Configuring safe-0.3.9...
    Installed nats-1
    Configuring newtype-0.2...
    Installed network-info-0.2.0.7
    Building safe-0.3.9...
    Building newtype-0.2...
    Configuring strict-0.3.2...
    Installed safe-0.3.9
    Configuring system-filepath-0.4.13.4...
    Installed newtype-0.2
    Building strict-0.3.2...
    Configuring th-expand-syns-0.3.0.6...
    Installed strict-0.3.2
    Building th-expand-syns-0.3.0.6...
    Configuring tar-0.4.2.1...
    Installed th-expand-syns-0.3.0.6
    Configuring th-lift-0.7.2...
    Installed SHA-1.6.4.2
    Building tar-0.4.2.1...
    Building th-lift-0.7.2...
    Configuring uniplate-1.6.12...
    Installed th-lift-0.7.2
    Configuring utf8-string-1...
    Installed tar-0.4.2.1
    Building uniplate-1.6.12...
    Building system-filepath-0.4.13.4...
    Building utf8-string-1...
    Configuring unix-compat-0.4.1.4...
    Installed utf8-string-1
    Building unix-compat-0.4.1.4...
    Configuring uuid-types-1.0.2...
    Installed unix-compat-0.4.1.4
    Configuring transformers-compat-0.4.0.4...
    Installed uniplate-1.6.12
    Building uuid-types-1.0.2...
    Building transformers-compat-0.4.0.4...
    Configuring cryptohash-0.11.6...
    Installed uuid-types-1.0.2
    Building cryptohash-0.11.6...
    Installed transformers-compat-0.4.0.4
    Configuring pem-0.2.2...
    Building pem-0.2.2...
    Installed pem-0.2.2
    Configuring http-types-0.8.6...
    Building http-types-0.8.6...
    Configuring streaming-commons-0.1.12.1...
    Installed system-filepath-0.4.13.4
    Configuring cookie-0.4.1.6...
    Installed cryptohash-0.11.6
    Building streaming-commons-0.1.12.1...
    Configuring socks-0.5.4...
    Installed http-types-0.8.6
    Building cookie-0.4.1.6...
    Building socks-0.5.4...
    Installed cookie-0.4.1.6
    Configuring aeson-0.7.0.6...
    Building aeson-0.7.0.6...
    Configuring asn1-types-0.3.0...
    Installed socks-0.5.4
    Configuring cryptonite-0.6...
    Installed streaming-commons-0.1.12.1
    Building asn1-types-0.3.0...
    Building cryptonite-0.6...
    Configuring semigroups-0.16.2.2...
    Installed asn1-types-0.3.0
    Building semigroups-0.16.2.2...
    Configuring constraints-0.4.1.3...
    Installed semigroups-0.16.2.2
    Building constraints-0.4.1.3...
    Configuring th-reify-many-0.1.3...
    Installed constraints-0.4.1.3
    Building th-reify-many-0.1.3...
    Installed th-reify-many-0.1.3
    Configuring exceptions-0.8.0.2...
    Building exceptions-0.8.0.2...
    Configuring transformers-base-0.4.4...
    Installed aeson-0.7.0.6
    Configuring system-argv0-0.1.1...
    Installed exceptions-0.8.0.2
    Building transformers-base-0.4.4...
    Configuring system-fileio-0.3.16.3...
    Installed transformers-base-0.4.4
    Building system-argv0-0.1.1...
    Configuring uuid-1.3.11...
    Installed system-argv0-0.1.1
    Building system-fileio-0.3.16.3...
    Building uuid-1.3.11...
    Configuring asn1-encoding-0.9.0...
    Installed system-fileio-0.3.16.3
    Installed uuid-1.3.11
    Configuring th-orphans-0.12.2...
    Configuring http-client-0.4.20...
    Installed cryptonite-0.6
    Building asn1-encoding-0.9.0...
    Building th-orphans-0.12.2...
    Building http-client-0.4.20...
    Configuring zeromq4-haskell-0.6.3...
    Installed asn1-encoding-0.9.0
    Building zeromq4-haskell-0.6.3...
    Configuring monad-control-1.0.0.4...
    Installed zeromq4-haskell-0.6.3
    Installed th-orphans-0.12.2
    Configuring asn1-parse-0.9.1...
    Configuring ipython-kernel-0.6.1.2...
    Installed http-client-0.4.20
    Building monad-control-1.0.0.4...
    Building asn1-parse-0.9.1...
    Building ipython-kernel-0.6.1.2...
    Installed monad-control-1.0.0.4
    Configuring lifted-base-0.2.3.6...
    Installed asn1-parse-0.9.1
    Configuring x509-1.6.0...
    Building lifted-base-0.2.3.6...
    Building x509-1.6.0...
    Installed lifted-base-0.2.3.6
    Configuring enclosed-exceptions-1.0.1.1...
    Building enclosed-exceptions-1.0.1.1...
    Configuring lifted-async-0.7.0.1...
    Installed enclosed-exceptions-1.0.1.1
    Installed ipython-kernel-0.6.1.2
    Building lifted-async-0.7.0.1...
    Installed x509-1.6.0
    Configuring x509-store-1.6.0...
    Building x509-store-1.6.0...
    Installed lifted-async-0.7.0.1
    Configuring shelly-1.6.3.3...
    Installed x509-store-1.6.0
    Configuring x509-system-1.6.0...
    Configuring x509-validation-1.6.0...
    Building shelly-1.6.3.3...
    Building x509-system-1.6.0...
    Building x509-validation-1.6.0...
    Installed x509-system-1.6.0
    Installed x509-validation-1.6.0
    Configuring tls-1.3.1...
    Building tls-1.3.1...
    Installed shelly-1.6.3.3
    Installed haskell-src-exts-1.16.0.1
    Configuring haskell-src-meta-0.6.0.10...
    Configuring hlint-1.9.21...
    Installed tls-1.3.1
    Configuring connection-0.2.5...
    Building haskell-src-meta-0.6.0.10...
    Building hlint-1.9.21...
    Building connection-0.2.5...
    Installed connection-0.2.5
    Configuring http-client-tls-0.2.2...
    Installed haskell-src-meta-0.6.0.10
    Configuring here-1.2.7...
    Building http-client-tls-0.2.2...
    Building here-1.2.7...
    Installed http-client-tls-0.2.2
    Installed here-1.2.7
    Installed hlint-1.9.21
    cabal: user error (Error: some packages failed to install:
    ghc-parser-0.1.7.0 failed during the building phase. The exception was:
    ExitFailure 1
    ihaskell-0.6.4.1 depends on ghc-parser-0.1.7.0 which failed to install.
    )

**Comment by gibiansky** [comment]
I think this may indeed be a real issue. Install from Github for the time being, I will try to get this fixed soon.

**Comment by gibiansky** [comment]
Try newly uploaded `ghc-parser` if you'd like.
